# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: profile.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rprofile.proto\x12\x07profile\"r\n\x14\x43reateProfileRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x62io\x18\x03 \x01(\t\x12\x10\n\x08pronouns\x18\x04 \x01(\t\x12!\n\x07socials\x18\x05 \x01(\x0e\x32\x10.profile.Socials\";\n\x15\x43reateProfileResponse\x12\x10\n\x08mongo_id\x18\x01 \x01(\t\x12\x10\n\x08recieved\x18\x02 \x01(\x08*%\n\x07Socials\x12\x0b\n\x07TWITTER\x10\x00\x12\r\n\tINSTAGRAM\x10\x01\x32R\n\x07Profile\x12G\n\x06\x43reate\x12\x1d.profile.CreateProfileRequest\x1a\x1e.profile.CreateProfileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'profile_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SOCIALS']._serialized_start=203
  _globals['_SOCIALS']._serialized_end=240
  _globals['_CREATEPROFILEREQUEST']._serialized_start=26
  _globals['_CREATEPROFILEREQUEST']._serialized_end=140
  _globals['_CREATEPROFILERESPONSE']._serialized_start=142
  _globals['_CREATEPROFILERESPONSE']._serialized_end=201
  _globals['_PROFILE']._serialized_start=242
  _globals['_PROFILE']._serialized_end=324
# @@protoc_insertion_point(module_scope)
