# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: profile.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rprofile.proto\x12\x07profile\"^\n\x0eProfileRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0b\n\x03\x62io\x18\x03 \x01(\t\x12\x10\n\x08pronouns\x18\x04 \x01(\t\x12\x13\n\x0bprofile_pic\x18\x05 \x01(\x0c\"4\n\x0fProfileResponse\x12\x10\n\x08mongo_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x32G\n\x07Profile\x12<\n\x07Profile\x12\x17.profile.ProfileRequest\x1a\x18.profile.ProfileResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'profile_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PROFILEREQUEST']._serialized_start=26
  _globals['_PROFILEREQUEST']._serialized_end=120
  _globals['_PROFILERESPONSE']._serialized_start=122
  _globals['_PROFILERESPONSE']._serialized_end=174
  _globals['_PROFILE']._serialized_start=176
  _globals['_PROFILE']._serialized_end=247
# @@protoc_insertion_point(module_scope)
